# 你服务器通常使用的语言
# zh_cn = 简体中文 / zh_tw = 繁体中文
SERVER-LANGUAGE: zh_cn

# 当玩家切换客户端语言时，是否提醒切换服务端语言支持？
NOTIFY: true

# 翻译功能是否启用
TRANSLATIONS:
  ITEM: true
  TITLE: true
  TABLIST: true
  CHAT: true
  SCOREBOARD: true
