# 常规设置
GENERAL:
  # 是否自动检测更新? (推荐开启)
  CHECK-UPDATE: true
  # 你的服务器内容适用的中文类型？
  # zh_cn = 简体中文 / zh_tw = 繁体中文
  # 只有当玩家设定语言≠服务器语言时才会翻译包
  SERVER-LANGUAGE: zh_cn

# 当玩家切换客户端语言时，是否提醒切换服务端语言支持？
NOTIFY: true

# 翻译功能是否启用
# 启用的项玩家也可通过一个GUI自由开关切换
TRANSLATIONS:
  # 聊天
  CHAT: true
  # 物品
  ITEM: true
  # 标题
  TITLE: true
  # Tablist
  TABLIST: true
  # 记分板
  SCOREBOARD: true

# 部分选项
OPTIONS:
  # 是否只翻译系统菜单GUI中的物品？
  # 启用此项可减少翻译量, 但将不会翻译玩家背包里的物品
  GUI-ONLY: true